# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

gem "middleman" , "~>3.2"
# gem 'middleman-ngmin', github: 'bhollis/middleman-ngmin'
gem 'slim' #, '~> 1.3.7'
gem 'rb-inotify', '~> 0.9', require:  RUBY_PLATFORM.include?('linux') ? 'rb-inotify' : false
gem 'poltergeist', '~> 1.5.0'
gem 'capybara'
gem 'rspec'
gem 'pry'
gem 'oj'
gem 'uglifier'
